package tracker.models;

public enum Endpoint {
    GET_ALL_TASKS,
    GET_ONE_TASK,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED,
    GET_ALL_SUBTASKS,
    GET_ONE_SUBTASK,
    GET_ALL_EPICS,
    GET_ONE_EPIC,
    POST_TASK,
    POST_EPIC,
    POST_SUBTASK,
    DELETE_ONE_TASK,
    DELETE_ONE_EPIC,
    DELETE_ONE_SUBTASK,
    DELETE_ALL_TASKS,
    DELETE_ALL_EPICS,
    DELETE_ALL_SUBTASKS,
    UNKNOWN
}